trigger:
  branches:
    include:
    - refs/heads/main
resources:
  repositories:
  - repository: self
    type: git
    ref: refs/heads/main
jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    vmImage: windows-2019
  steps:
  - checkout: self
    clean: true
  - task: TerraformInstaller@0
    displayName: Terraform latest
  - task: TerraformCLI@0
    displayName: terraform init
    inputs:
      command: init
      backendType: azurerm
      backendServiceArm: 8caafed1-206a-48ea-b1f6-9fbbd7aee304
      backendAzureRmSubscriptionId: 5a0855b9-426d-429e-83a9-ea7c4796e9a4
      backendAzureRmResourceGroupName: RG12
      backendAzureRmStorageAccountName: strinfraterra
      backendAzureRmContainerName: tstate
      backendAzureRmKey: woGcRW115oKYd+fQB3wjTWIiD2/54vKa/0YME7ns+T0HcR/lZO89XEvGXare+/1FS7hGKF/htqa3+ASt0fAGxw==
  - task: TerraformCLI@0
    displayName: terraform plan
    inputs:
      command: plan
      environmentServiceName: 8caafed1-206a-48ea-b1f6-9fbbd7aee304
      providerAzureRmSubscriptionId: 5a0855b9-426d-429e-83a9-ea7c4796e9a4
      providerGoogleProject: DevOps-MC-lab-In-CI
      providerGoogleRegion: northeurope
  - task: TerraformCLI@0
    displayName: terraform apply
    inputs:
      command: apply
      environmentServiceName: 8caafed1-206a-48ea-b1f6-9fbbd7aee304
      providerAzureRmSubscriptionId: 5a0855b9-426d-429e-83a9-ea7c4796e9a4
      providerGoogleProject: DevOps-MC-lab-IN-CI
      providerGoogleRegion: northeurope
...
